### ISSUE TITLE
PHP error on registration (clean install and demo site)

### ISSUE THREAD

**Issue by oliversiegel** [b2evolution/b2evolution#104]
When trying to register a new account, both on my clean localhost install, but also on the public demo site, I get this error:

Fatal error: Call to a member function get_skin_ID() on boolean in /home/b2evodemo/www/stable/htsrv/register.php on line 835

**Comment by fplanque** [comment]
Please show a screenshot of where you last clicked before the error, on your local install.

We also need the exact b2evo version you use.

**Comment by oliversiegel** [comment]
7.1.5-stable-2020-05-01

![image](https://user-images.githubusercontent.com/35322693/83693046-11360e00-a5aa-11ea-8341-6141b9b55d2d.png)

**Comment by fplanque** [comment]
Something must be special in your setup. It works be default as you can see here: http://demo2.b2evolution.net/stable/index.php/forums/

Please reset your collection for registering here: http://demo2.b2evolution.net/stable/evoadm.php?ctrl=collections&tab=site_settings

Man page: https://b2evolution.net/man/default-collections

**Comment by oliversiegel** [comment]
When I click register here, I get the same error: 

http://demo2.b2evolution.net/stable/evoadm.php?ctrl=dashboard

And I got there via:
1. https://b2evolution.net/
2. Demo in the Top Menu
3. Access Demo Site
4. Go to dashboard and start creating

**Comment by oliversiegel** [comment]
The links you posted:
 http://demo2.b2evolution.net/stable/index.php/forums/

There is no "register" button.
But when I click "Go to dashboard and start creating" then I see a register button, upon which I get the error.

When I click "register" here
http://demo2.b2evolution.net/stable/evoadm.php?ctrl=collections&tab=site_settings
I also get the error

**Comment by fplanque** [comment]
Indeed you have to create demo contents before you can see Register buttons in the front office.

There is no "register" to click on the URLs you post. Example:

<img width="1502" alt="2020-06-04_14-01-08" src="https://user-images.githubusercontent.com/1156771/83754263-f88e2c80-a66b-11ea-9183-93e4852486be.png">

Also, you completely ignored my instructions here: https://github.com/b2evolution/b2evolution/issues/104#issuecomment-638499755

**Comment by fplanque** [comment]
You can work around the bugs with the procedure I gave above, however I confirm the bugs are real. They have been fixed in GitHub and will be in the next release.
