### ISSUE TITLE
Site skin template [_site_body_header.inc.php] not found

### ISSUE THREAD

**Issue by Metztli** [b2evolution/b2evolution#107]
Niltze [Hello]-
If you enter in a search engine field the above string, and select (click) on the link, you will realize that a desktop browser will not show the bug; but visiting with an Android device the bug will be glaringly evident -- as well as "Site skin template [_site_body_footer.inc.php] not found" -- in the bootstrap skins which come with b2evolution 7.1.5 and which obviously are being used by the sites manifesting the issue, i.e., http://www.landbeyond.net/arx .
![issue_b2evo-7_1_5](https://user-images.githubusercontent.com/3677052/88658241-f783e500-d087-11ea-9a8e-4a4598a72403.png)
![issue-b2evo-7_1_5_](https://user-images.githubusercontent.com/3677052/88658266-01a5e380-d088-11ea-9887-d56a2a050126.png)

A search engine which shows those terms for a b2evolution site is not good for SEO and/or owners of those sites.

Please note that by going to the skin tab and deselecting *only* the Footer container, then it improves the site display in an Android mobile device as "Site skin template [_site_body_footer.inc.php] not found" does not show anymore *and* apparently splashing/cloaking with white the string "Site skin template [_site_body_header.inc.php] not found"; notwithstanding, that is merely a workaround since by deselecting the Header container, as well, then *both* bug strings display again.
![shot-2020-07-26_11-29-46](https://user-images.githubusercontent.com/3677052/88659452-eb992280-d089-11ea-8119-cdff382af6f7.jpg)

Best Professional Regards.

**Comment by fplanque** [comment]
b2evolution can use a different skin for desktop and for mobile. None of your screenshots shows which skins are configured for each case.

**Comment by Metztli** [comment]
I have no control over the first site cited. I simple entered a search for the string of reference --as it was being shown in Android device 6.0.1 in another b2evo 7.1.5 upgraded site and it came out as another result.

On the other hand, in the Bootstrap Photoblog Skin tab, of a site that I am able to modify and that came out in the search results -- I just disabled all boxes under the section: "When access is denied or requires log in..." and the errors in both mobile Google Chrome and desktop browsers, i.e., Firefox, Yandex-Browser, Google Chrome, Seamonkey, are all gone. I will continue to monitor the issue but if it was not a bug but a lack of action on the skin of reference, I apologize. Notwithstanding, a couple of days back the only change that would make a difference was the one cited initially.
![out](https://user-images.githubusercontent.com/3677052/88673433-746d8980-d09d-11ea-83cf-4101ad058cf7.png)

Thank you.

**Comment by Metztli** [comment]
The issue has an affinity to default Bootstrap b2evolution 7.1.5 skins (please see other search results attached) because after a while (b2evolution cache relevant?) the issues remains constant, i.e.,  
Site skin template [_site_body_header.inc.php] not found
and
Site skin template [_site_body_footer.inc.php] not found

and "bubble up" to be picked up by search engine(s)
![Site_skin_template_-_site_body_header inc php-_not_found](https://user-images.githubusercontent.com/3677052/88725666-51fd5f80-d0e1-11ea-9e2f-5c1a8519bfa5.jpg)

Please, note, that I have not experienced the issue with other skins, i.e., Business, etc.

Thank you.

**Comment by fplanque** [comment]
Do you know how to reproduce on a fresh install?

**Comment by Metztli** [comment]
Probably. I am working on a site with an IP only and later I could give it domain name -- if only ephemerally -- for the mobile device to display the issue of reference. Nevertheless, I visited the sites found by the search engine and they are not 'fresh installs' but rather seem upgraded. Their admins probably have not noticed the alleged bug *because* it is glaring only with a mobile device; if you visit them with a desktop browser the string is mostly hidden -- but not for the search engines, obviously.

**Comment by fplanque** [comment]
If you know how to reproduce, please list the steps to do after a fresh install.

**Comment by Metztli** [comment]
Fact is people seldom do a 'fresh install' and the upgrade actually introduces conflicts with already *pre-existing* settings/customizations that your b2evo fans have invested considerable time to have their b2evo sites to their presentation liking.

As a matter of fact, the error(s) of reference only manifested in certain collections and/or varied paths during clicking a link(s) after the upgrade to 7.1.5/6. Many of your b2evo fans whose sites show up on the Internet search engines due to this unfortunate string error are not even aware that it's happening. Moreover for your b2evo fans who had a site wide header and footer working perfectly before the upgrade, they suddenly realize that it does not work anymore because certain collections even with Bootstrap defaults basically puke the error when they are not looking.

With that behind, the somewhat acceptable way to resolve the mobile device error display issue is by going to the Site --> Site settings, scrolling down to *uncheck* the "Enable site skins: [] Enables a sitewide header and footer". Heck that is not optimal for the reasons stated 'a priori' but at least your b2evo fans will avoid the errors being shown to others behind their back.
![_site_body_header inc php](https://user-images.githubusercontent.com/3677052/88881468-578f9e00-d1e4-11ea-8615-e6e9fe719b41.jpg)

**Comment by fplanque** [comment]
So besides all the drama (which I personally have no interest in reading nor replying to):

1. I understand the bug cannot be reproduced on a fresh install
2. I understand the bug can probably be reproduced by installing an older version and then upgrading it. If you have identified a complete path to reproduce, please list the steps in order.
