### ISSUE TITLE
/inc/_core/ui/forms/_form.class.php shows error on bootstrap skin contact form

### ISSUE THREAD

**Issue by Metztli** [b2evolution/b2evolution#11]
Only happens with the Bootstrap skin; but not the Bootstrap Blog displaying same collection; following output is shown anywhere with Contact form:

 /var/www/b2evolution/inc/_core/ui/forms/_form.class.php on line 303
if I nullify the offending line with /**  */
then 
/var/www/b2evolution/inc/_core/ui/forms/_form.class.php on line 2816
thus I nullify the offending line /** */

and error is not shown anymore. I know my hack is temporary and I hope I will not mess other skins.

Best Professional Regards.

**Comment by fplanque** [comment]
Your error Message is not complete. Wie know there is an error ob Line 303 but you die bot copy/paste the nature of the error. Please do. Even better would be a screenshot.

Also please confirm you b2evolution version and PHP version.

**Comment by Metztli** [comment]
B2evolution 6.6.1 and
php --version
PHP 5.4.41-0+deb7u1 (cli) (built: May 22 2015 12:49:18)

Attached partial snapshots are of the same item in same Collection -- but using different skins:

Bootstrap skin: error appears anywhere a contact form is present
vs
Bootstrap Blog skin: no error

Thanks!
![bootstrap_pseudo-blog](https://cloud.githubusercontent.com/assets/3677052/9049972/27cec4e0-39fd-11e5-8335-9ae1121e320f.png)
![bootstrap_blog](https://cloud.githubusercontent.com/assets/3677052/9049977/376f511c-39fd-11e5-9ee1-958dbf0e8d0b.png)

**Comment by fplanque** [comment]
Ok, so the problem is with the **comment** form, not the **contact** form.

Thanks for reporting. We'll fix this.

**Comment by fplanque** [comment]
Oh wait. The bootstrap skin is obsolete. It has been replaced by the bootstrap_blog skin. Please use this one. It does the same thing.

**Comment by Metztli** [comment]
Sorry about that. I should have taken care to remove that as was indicated by the documentation -- *before* users complained in turn to me.

Issue is closed, my bad.
