### ISSUE TITLE
The project is dead?

### ISSUE THREAD

**Issue by thelacesz** [b2evolution/b2evolution#113]
Dear Developer,

I would like to ask if the project is dead? We see no progress.

Regards,
Laszlo

**Comment by TheNomad11** [comment]
More or less, see here https://fplanque.com/dev/b2evolution/18-years-of-b2evolution and https://forums.b2evolution.net/what-has-happened-last-year-to-b2e

**Comment by thelacesz** [comment]
Thank you very much!
