### ISSUE TITLE
Auto Update to 7.2.4

### ISSUE THREAD

**Issue by jekewa** [b2evolution/b2evolution#116]
I ran an auto-update on my server from the UI, and it found and downloaded a version that I don't see on the [https://b2evolution.net/downloads/](https://b2evolution.net/downloads/) or here in [https;//github.com/b2evolution/b2evolution/tags](https://github.com/b2evolution/b2evolution/tags). I should have checked those sources first, but haven't ever had doubts in the past. I discovered this as I was working to update [my Docker image](https://github.com/jekewa/b2evolution) from 7.2.3-stable, but couldn't find mention of the new version.

Is this intentional, maybe with an oversight on the GitHub tags and blog? Or is this some potential intrusion that someone perpetrated? 

This is what the Docker image reports on the System Status page, which all looks savvy.

```
b2evolution version
7.2.3-stable released on 2021-03-01 

b2evolution version 7.2.4-stable-2022-03-26 is now available. For best security, we strongly recommend that you [upgrade](http://localhost/evoadm.php?ctrl=upgrade) to the latest version. [Download here](http://b2evolution.net/downloads/).
```

The upgrade seems to have worked. I'm hesitant to replace it with the 7.2.3 version in case the 7.2.4 version (legit or otherwise) changed the DB.

**Comment by fplanque** [comment]
It is intentional that auto update serves this version before we make it public.
