### ISSUE TITLE
Multiple use of tags in the FrontOffice - how to solve this problem

### ISSUE THREAD

**Issue by AlexL777** [b2evolution/b2evolution#15]
Hello Developers,

I've got a problem with the version 6.7.0 Alpha. In the front office, the tags below the blog post are displayed multiple times. For this purpose, please follow this URL:> http://alexliebrecht.com/blogs/blog1.php/b2evolution-6-7-0-alpha-erschienen-upgrade-war-funktionell#more131

And I will show you even more in the screenshot.

There are simply a number of times the tags displayed and I still do not know how to control it in the back office. Have you as a tip or is it a bug?

![tagging-b2evolution-cms-670alpha](https://cloud.githubusercontent.com/assets/7885632/12178147/4028277c-b570-11e5-840f-edfeaa7030e4.jpg)

**Comment by AlexL777** [comment]
Has just finished and I had to install the bootstrap design again. That looks now under the blog post from normal and the tags are displayed only once. That fits me like that.

**Comment by fplanque** [comment]
It is a matter of which widgets are in the Single Post container.
