### ISSUE TITLE
"Post Statuses" menu item error

### ISSUE THREAD

**Issue by Metztli** [b2evolution/b2evolution#19]
On B2evo 6.6.7 stable

Selecting **Collections** (from next to last upper menu)
then select lower **Settings** tab
proceed to select **Post Statuses** from lower menu

And the error below appears:

Warning: require(/var/www/b2evolution/inc/items/views/_itemstatuses.view.php): failed to open stream: No such file or directory in /var/www/b2evolution/skins_adm/_adminUI_general.class.php on line 711

Fatal error: require(): Failed opening required '/var/www/b2evolution/inc/items/views/_itemstatuses.view.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/b2evolution/skins_adm/_adminUI_general.class.php on line 711

Thanks for your consideration.

**Comment by hhren1984** [comment]
1. Please check the file '/var/www/b2evolution/inc/items/views/_itemstatuses.view.php' exists.
2. If it exists, check the read permission of this file. Maybe it can be readable by your HTTP SERVER default user.

**Comment by Metztli** [comment]
Thank you.
_itemstatuses.view.php
_itemstatus.form.php
were not there (!?) and fetched them from a current b2evo-6.6.7 stable.

Best Professional Regards.
