### ISSUE TITLE
PHP 5.2.11 met the error : "Strict Standards: is_a(): Deprecated. Please use the instanceof operator in b2/inc/_ext/xmlrpc/_xmlrpc.inc.php on line 2201"

### ISSUE THREAD

**Issue by hhren1984** [b2evolution/b2evolution#21]
> NOTE: This error only showing in develop branch, and the php version is php5.2.11.

The reason why I submit this error is that it's may be only small probability events which only happens in individual php versions. This may need master and developers to see it.

**Comment by hhren1984** [comment]
Change all 'is_a()' to to 'instanceof()' will be OK. 
is_a() is appropriate for PHP 4 >= 4.2.0, PHP 5>5.3.0
instanceof() is appropriate for PHP5 

Sometimes such things may drive anybody crazy.

**Comment by mgsolipa** [comment]
It's weird. Function is_a() was deprecated from 5.0.0 to 5.2 and then no longer deprecated on 5.3.0.

I think there is still some decisions to make regarding the minimum supported version of PHP for release 6.7.x  ( @fplanque ). So, if 5.3 (or higher) finally becomes the minimum requirement, then keeping is_a() might be ok.

In any case, I sent a pull request that might solve the problem: https://github.com/b2evolution/b2evolution/pull/22. Please see that is_a is used in many other places in the code, so if this solution is accepted, then we need to modify the rest of appearances.
