### ISSUE TITLE
403 Forbidden when using site-wide SSL

### ISSUE THREAD

**Issue by rpharrison** [b2evolution/b2evolution#23]
I've recently noticed a problem with SSL and 403 referer notices when searching my domain (puertomarino.es) in Google search.

Since the site switched to SSL, Google has deindexed most non-SSL search results, clicking through gives me the 403 error. At this point I can use the bypass, or change https:// on the current page to http://.

It seems like visiting from a https:// link in Google doesn't work because b2evo expects the url to be http://

Any help with this would be appreciated.

**Comment by mgsolipa** [comment]
@rpharrison it seems that, for some unknown reason, you have blacklisted google.es in your antispam list (http://b2evolution.net/man/back-office-reference/system/antispam-tab/), and your "Block spam referrers" parameter is enabled (http://b2evolution.net/man/back-office-reference/system/antispam-tab/antispam-settings/).

You have two options: 1) Remove google.es from the blacklist (I think you should do it). 2) Disable "Block spam referrers".

**Comment by mgsolipa** [comment]
@rpharrison in addition to above, writing here is ok, but the forums (http://forums.b2evolution.net/) is a better place to ask for support. Even for bug reports and any other interaction.

Regards!

**Comment by rpharrison** [comment]
@mgsolipa I'd thought it might be the blacklist too, having previously searched it for "google" (realising any blacklisted url containing it would block). This is the results if I search the blacklist:

![b2-blacklist](https://cloud.githubusercontent.com/assets/3842018/15023129/51a47052-122f-11e6-9e6a-d419833f923e.jpg)

**Comment by rpharrison** [comment]
@mgsolipa On the referring domains tab I searched google again, making all entries trusted, yet the block remains. It's only been happening since the version where the backoffice UI changed (2 versions back I think?).

**Comment by fplanque** [comment]
I am closing this because it's a one year old support question.
If there's still a problem,  please seek support on http://forums.b2evolution.net/
