### ISSUE TITLE
Blog's cache setting info while cache folder do not exists

### ISSUE THREAD

**Issue by tjancz** [b2evolution/b2evolution#27]
Hello

If there is a problem with:
$result = system_check_dir( 'cache', 'c'.$blog_ID.'/' );  in _system.funcs.php
there should be added info in message with full patch of the missing folder, so admin could create it instead of general message that folder is missing.

Best regards
TJ

**Comment by fplanque** [comment]
You didn't post a screenshot and didn't give a line number but as a general rule, messages will be displayed with full paths in the back-office. When a message is potentially displayed in the front office, it does not show a full path for security reasons.
