### ISSUE TITLE
A SMALL BUG in inc\skins\_skin.funcs.php

### ISSUE THREAD

**Issue by hhren1984** [b2evolution/b2evolution#29]
inc\skins\_skin.funcs.php about line : 640
```
					$recipients_selected = array( array(
							'id'    => $recipient_User->ID,
							'title' => $recipient_User->login,
						) );
```
the 'title' should be changed to 'login'

This small bug may cause the problem that we can't show the real recipient username directly by the url with recipient_id param, it would be shown as 'undefined'.

**Comment by fplanque** [comment]
Thank you, this was fixed here: https://github.com/b2evolution/b2evolution/commit/46d275523bcb8e289642240f38ff6a2161f8180f
