### ISSUE TITLE
Bug in file _user.class.php

### ISSUE THREAD

**Issue by AppChecker** [b2evolution/b2evolution#30]
Hi,

[function check_perm_blog_global, file inc/users/model/_user.class.php](https://github.com/b2evolution/b2evolution/blob/63198e5208a225a4d7689569db7d963efeba654b/inc/users/model/_user.class.php#L3049):
` ( $permlevel == 'view' && $permlevel == 'any' ) `
This expression always false. May be it should be 
` ( $permlevel == 'view' || $permlevel == 'any' ) `
?

This possible defect found by [AppChecker](https://cnpo.ru/en/solutions/appchecker.php)

**Comment by fplanque** [comment]
Thanks. This has been fixed here: https://github.com/b2evolution/b2evolution/commit/0db45facdc34b876ccc1a5fbd2be7a36d9732cab
