### ISSUE TITLE
Broken link for "Remove orphan file roots"

### ISSUE THREAD

**Issue by davidnewcomb** [b2evolution/b2evolution#31]
Version: 6.7.4-stable

In the maintenance section, clicking "Find and delete all orphan Comments (with no matching Item) - Disk & DB." sends you to a page with a broken link.

![screen shot 2016-07-27 at 18 51 30](https://cloud.githubusercontent.com/assets/951359/17187292/8c183316-5430-11e6-9bbc-a9f1414fe992.png)

The url link is missing "?" after admin.php

**Comment by fplanque** [comment]
Thanks. This has been fixed here: https://github.com/b2evolution/b2evolution/commit/c2a158c71f9415ec4912a0694e56fbe92a49dd61
