### ISSUE TITLE
Plugin class uses pass-by-reference signatures

### ISSUE THREAD

**Issue by blueyed** [b2evolution/b2evolution#32]
I have been notified that one of my old plugin throws E_STRICT errors by now:

> Strict Standards: Declaration of captcha_img_plugin::GetDefaultSettings() should be compatible with Plugin::GetDefaultSettings(&$params) in …

But adhering to this does not work, since then you get a fatal error:

> Fatal error: Call-time pass-by-reference has been removed

So while you apparently tend to not enable strict errors, some users do.

I think the fix would be to adjust the function declaration in the `Plugin` base class.

**Comment by fplanque** [comment]
You report that you get:

> Fatal error: Call-time pass-by-reference has been removed

In what file and what line do you get this please? (and in what branch, if not master)

Thanks.

**Comment by blueyed** [comment]
I am not getting it, but a user that changed the deriving plugin's function definition to e.g. `GetDefaultSettings(&params)` (IIRC, the important part is also using the "&params" here, like in the Plugin class, which triggers the strict warning).

But then this should also happen with e.g. https://github.com/b2evolution/b2evolution/blob/master/plugins/cookie_consent_plugin/_cookie_consent.plugin.php#L50.

So probably he did not modify the plugin correctly, and I confused pass-by-reference with pass-by-value.
The plugin is https://sourceforge.net/p/evocms-plugins/code/HEAD/tree/captcha_img_plugin/trunk/_captcha_img.plugin.php btw.

Closing for now.  Sorry for the noise.

Apparently the plugin

**Comment by blueyed** [comment]
It's this issue: http://forums.b2evolution.net/update-from-6-6-8-to-6-7
