### ISSUE TITLE
some vulnerabilities

### ISSUE THREAD

**Issue by phantom0301** [b2evolution/b2evolution#34]
Hi
I find some Vulnerabilities in b2evolution CMS’s upload policy.
First, all upload filename will not be modifed. It means attacker can guess where the upload file in.
Second, comment and avadar allow upload swf file and the swf file will execute by flowplayer_plugin. We know, we can insert script code in flash swf, it means we can code execute through swf file.

**Comment by fplanque** [comment]
I sent you an email, did you get it?

**Comment by fplanque** [comment]
1) we will change the `swf` file type to be uploadable only by admins.

2) why is it bad that attackers can "guess" where the file is uploaded? The files will be displayed immediately after upload, so what's the point of hiding them?

**Comment by phantom0301** [comment]
Hi
I am sorry for posting them on security sites, github. It's my mistake.
If a user upload his file on the site. Usually, we will random the filename and make the user not know the random filename. It means you can upload file and the program can use your file but you don't konw where it in. 
Maybe our program filter the dangerous file type.But if attacker bypass the filter function and they know the file path, he can get shell successfully.
So we random the filename to make attacker can't get the file path.
----- 原始邮件 -----
发件人：Francois Planque <notifications@github.com>
收件人：b2evolution/b2evolution <b2evolution@noreply.github.com>
抄送人：phantom0301 <phantom0309@sina.com>,  Author <author@noreply.github.com>
主题：Re: [b2evolution/b2evolution] some vulnerabilities (#34)
日期：2017年01月15日 10点13分



we will change the swf file type to be uploadable only by admins.


why is it bad that attackers can "guess" where the file is uploaded? The files will be displayed immediately after upload, so what's the point of hiding them?



&mdash;

**Comment by fplanque** [comment]
https://github.com/b2evolution/b2evolution/commit/261dbd5b294e707af766691e65a177a290314a6e

**Comment by fplanque** [comment]
Fix released: http://b2evolution.net/downloads/6-8-4
