### ISSUE TITLE
Possible bugs in source code (CWE-398)

### ISSUE THREAD

**Issue by AppChecker** [b2evolution/b2evolution#45]
Hello!

We've checked your code with [AppChecker static analyzer](https://cnpo.ru/en/solutions/appchecker.php) and found possible bugs:

1)
https://github.com/b2evolution/b2evolution/blob/1338e3b71946850acc593b50061786bf6b38ed90/inc/xmlrpc/model/_xmlrpcs.funcs.php#L367

```
        if( $parent_Item = & $ItemCache->get_by_ID( $Item->parent_ID, false, false ) );
        {
            $parent_title = $parent_Item->title;
        }
```
if-statement is empty because of the ';'.

2)
https://github.com/b2evolution/b2evolution/blob/1338e3b71946850acc593b50061786bf6b38ed90/inc/locales/_charset.funcs.php#L117

```
            if( $tmp_str = strtr( $str, $locales[$our_locale]['transliteration_map'] ) );
            {    // Use newly transliterated string
                $str = $tmp_str;
            }
```
if-statement is empty because of the ';'.

Possible defects were found by Echelon Team with [AppChecker static analyzer](https://cnpo.ru/en/solutions/appchecker.php)

**Comment by fplanque** [comment]
@yurabakhtin If this is not already fixed, please fix.

**Comment by yurabakhtin** [comment]
@fplanque These have been already fixed in commit https://github.com/b2evolution/b2evolution/commit/35390dda8ce1cb2a7c04d89511c97cab10a5e8ed 1 year ago.
