### ISSUE TITLE
PHP Warning:  Creating default object from empty value

### ISSUE THREAD

**Issue by sam2kb** [b2evolution/b2evolution#46]
The warning comes from /inc/links/model/_linkowner.class.php on line 130
A class needs to be initialized before we add any properties

`$this->link_Object = new stdClass();`

**Comment by fplanque** [comment]
@yurabakhtin if this issue still exists, please fix it.

**Comment by yurabakhtin** [comment]
@sam2kb I have done a fix to avoid such error in commit https://github.com/b2evolution/b2evolution/commit/777e7915c52f32f00033a4a508e4567c2b812458, but it would be good if you described how you got it.
