### ISSUE TITLE
The deprecation of create_function

### ISSUE THREAD

**Issue by keithbowes** [b2evolution/b2evolution#50]
`create_function` has been discouraged for a while now, since anonymous functions were added to PHP 5.3.  Now, `create_function` is [deprecated in PHP 7.2 and will be removed in PHP 8](https://wiki.php.net/rfc/deprecations_php_7_2).  I have a few ideas how to solve this in the b2evolution code base.
1. Use anonymous functions in future versions of b2evolution (users stuck with PHP 5.2.x can continue to use b2evolution 6.8.x).
2. Use a wrapper function, e.g.:
```php
if (!function_exists('create_anon_function'))
{
	function create_anon_function($args, $code)
	{
		if (class_exists('Closure'))
		{
			eval('$anon=function(' . $args . '){' . $code . '};');
			return $anon;
		}
		else
			return create_function($args, $code);
	}
```
Of course, this has the same problem as `create_function` itself; namely, it relies on the dangerous `eval`.
3. Replace all uses of `create_function` with named functions.
4. Continue to use `create_function` and note that the supported PHP versions are 5.2.0 to 7.1.x.

There's other deprecated functionality, but the others have much more straightforward fixes (e.g. using the `foreach` statement rather than the `each` function).

**Comment by fplanque** [comment]
@winskie Please use named functions everywhere (solution 3 above) in order to maximize compatibility with different PHP versions or let me know if this is too inconvenient.

**Comment by yurabakhtin** [comment]
@fplanque The uses of the function `create_function` are used in branch https://github.com/b2evolution/b2evolution/tree/release/6.9.x but all they already were replaced with named functions in commit https://github.com/b2evolution/b2evolution/commit/a9c8b6526366a99815f0462f1762d079392ae83d for the branch `6.10` https://github.com/b2evolution/b2evolution/tree/develop.

**Comment by fplanque** [comment]
@yurabakhtin ok, thanks for the info. I am closing this issue then.
