### ISSUE TITLE
 b2evolution/skins/bootstrap_photoblog_skin/_skin.class.php

### ISSUE THREAD

**Issue by Metztli** [b2evolution/b2evolution#52]
Niltze [Hello]

Please note that 

> #skin_wrapper

 introduced in 6.9.3 creates a bug where _Page link color_ and _Page link hover color_ are incorrectly inherited to the b2evolution Sitewide Header -- effectively disrupting font/link color consistency.

As a temporary hack, I reverted relevant

> body

directives below as in previous version 6.8.10 while proper fix in next b2evo version is done(hopefully).

_Line 436 (unmodified file)_
             // Page link color
                if ( $page_link_color = $this->get_setting( 'page_link_color' ) ) {
                // Jose/Metztli IT: 09-26-2017
                        // $custom_css .= '#skin_wrapper a, .evo_comment_title a, .panel-title .evo_comment_type { color: '.$page_link_color."; }\n";
                        $custom_css .= 'body a, .evo_comment_title a, .panel-title .evo_comment_type { color: '.$page_link_color."; }\n";
                }
_Line 440 (unmodified file)_
                // Page link hover color
                if ( $page_link_h_color = $this->get_setting( 'page_link_h_color' ) ) {
                // Jose/Metztli IT: 09-26-2017
                        // $custom_css .= '#skin_wrapper a:hover, .panel-title .evo_comment_type:hover { color: '.$page_link_h_color."; }\n";
                        $custom_css .= 'body a:hover, .panel-title .evo_comment_type:hover { color: '.$page_link_h_color."; }\n";
               }

Best Professional Regards.

**Comment by mgsolipa** [comment]
@Metztli can you please send details about how to reproduce the issue?

**Comment by Metztli** [comment]
@mgsolipa Sorry about the delay.

Images:
https://metztli.it/blog/index.php/amatl/aJ4

I just set up a new (default options) b2evo 6.9.3 installation in virtual machine:

**Collection Photos** default skin is Bootstrap Gallery Skin.
Select **Collection Photos** (observe mouse pointer) from the upper site bar: color of the other collection names remains the same.

[image 1]
Now go to Site Dashboard => Collections => Photos => Skin => Choose a different skin
=> Install new => (Select) Bootstrap Photoblog Skin

[image 2]
Observe how the color of *all* the other collection names -- actually every text string on the navigator bar -- turns to blue once the skin installs.

Of course, all the color collection names in the upper bar should not change color only because the skin of one collection changed.


Thanks.

**Comment by Metztli** [comment]
@mgsolipa,
Issue disappeared in b2evolution 6.9.4.

Thank you b2evolution developer team.
(Closing)
