### ISSUE TITLE
B2evo 6-9-5 Recent Images not showing after new Update

### ISSUE THREAD

**Issue by AlexL777** [b2evolution/b2evolution#62]
Hi Developers,

I do not know if this is a bug, but after updating to b2evo 6.9.5 "recent images" are no longer displayed in the frontend. I have already adjusted all rights on the Centos server and the media directory has CHMOD 775.

What could be the problem?

Maybe someone can help me.

Thanks in Advance.

![b2evo_6-9-5-recent-images-not-showing](https://user-images.githubusercontent.com/7885632/34473529-397fea82-ef74-11e7-8344-63eac0340201.png)

**Comment by fplanque** [comment]
What do you mean by "recent images". Is it a widget? If so, please provide a screenshot of the widget settings.
If not, please better describe your problem.
I don't know what I am supposed to see on your screenshot.

**Comment by AlexL777** [comment]
Thanks for the new Update on 6.9.6. My Problem is solved 👍
