### ISSUE TITLE
Installation fails if memory_limit = -1

### ISSUE THREAD

**Issue by davidnewcomb** [b2evolution/b2evolution#68]
If the php.ini has `memory_limit = -1` it means no limit, and not -1 MB of RAM like the installer suggests! -1 is generally set in development and production has an actual number. I think you should allow memory options of -1 as well as your requirement of 48MB. These days you will struggle to find a computer with less than 48MB!

**Comment by yurabakhtin** [comment]
@davidnewcomb Fixed in commit https://github.com/b2evolution/b2evolution/commit/f01348ddafe91e137fdd9a2bb34108e60dba9348.
