### ISSUE TITLE
Custom posts: new post creates a standard post

### ISSUE THREAD

**Issue by yafred** [b2evolution/b2evolution#8]
Hi,

I am exploring custom posts capabilities and I think I found a bug.

After creating a custom post and clicking on this custom post tab, the *New post* button links to something like *admin.php?ctrl=items&action=new&blog=2&item_typ_ID=1*

So it displays the standard post editor.

If you change item_typ_ID value with the value of the custom post, you can proceed and create a custom post successfully

**Comment by fplanque** [comment]
I confirm. I saw that bug myself a few days ago. The fix is currently #3 on our TODO list. Should be fixed this week.

The workaround in the meantime is to use the "change post type" in the top right corner.

**Comment by fplanque** [comment]
We have added our own, extended solution.

We are now adding permission management to creating post with custom types. Coming soon ;)
