### ISSUE TITLE
Request to non-existent blog number causes analytics log erasure.

### ISSUE THREAD

**Issue by Metztli** [b2evolution/b2evolution#80]
Niltze [Hello]

The following is typical of automated (and sometimes manual) attacks against b2evolution -- where specific number, i.e., 5469, may be *any* other non existing blog number at the site.
Request from the wild:
http://b2evo-hosting-site.com/blog/index.php/topic/specific/?blog=5469

Of course, there is no blog number 5469 and b2evo generates an error *and* also, in the Dashboard, wipes clean the analytics log up to the point in time where the invalid blog request number was done:

"An unexpected error has occurred!
If this error persists, please report it to the administrator.

Go back to home page"
(see attached clip)

As far as I recall this is a *known* bug in b2evo since years back. May I ask if it is in future road map to be fixed?
![unexpected-error](https://user-images.githubusercontent.com/3677052/40424413-61b157da-5e4a-11e8-8278-6dc6475b89fc.png)

Best Professional Regards.

**Comment by fplanque** [comment]
@Metztli When you say "wipes clean the analytics log", it means that data is deleted from the SQL database which I don't think is possible. There is no code to delete logs that can be access from the front office.

Do you mean, there is an error when you look at the log and the consequence is that the result of the results table does not show?

Please provide a full screen screenshot to show context, otherwise its usefulness is only 20% of what it could be.

**Comment by Metztli** [comment]
@fplanque 
After an error caused by a request to a non-existent blog number *all* the entries in the analytics Dashboard tab, i.e., Direct B-hits in this particular case, prior to the error disappear -- there is nothing to see below the wide 'unexpected error' entry. I was able to find the offending line by the date correlation with the relevant web server log entry.
![tab_direct_b-hits](https://user-images.githubusercontent.com/3677052/40433196-414245d4-5e60-11e8-9226-dd55756dda1b.png)

Notwithstanding, you can reproduce the above by inserting a non existing blog number into your query.
By the way, I got a couple of actual hits of the form:
http://b2evo-hosting-site.com/blog/index.php/topic/specific/?blog=1565
http://b2evo-hosting-site.com/blog/index.php/topic/specific/?blog=5469
at that specific time.

Thank you.

**Comment by yurabakhtin** [comment]
@fplanque @Metztli Fixed in commit https://github.com/b2evolution/b2evolution/commit/90d92a12c06e2080db9fbf31d2902a1f22b85aae.
