### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'UrlHelper' not found

### ISSUE THREAD

**Issue by Metztli** [b2evolution/b2evolution#82]
Niltze [Hello], Devs-

Unless I am missing a software package relevant to XML Feeds...

Nasty error logged to HTTPD / Apache2 error logs since b2evo-6.10.1 installation; when an rss reader and/or user accesses
https://site.com/b2evo-6.10.1/index.php?blog=4&tempskin=_rss2
error is logged as:

PHP Fatal error:  Uncaught Error: Class 'UrlHelper' not found in /server-path-to-b2evo-6.10.1/inc/_core/_url.funcs.php:760\nStack trace:\n#0 /server-path-to-b2evo-6.10.1/skins/_rss2/index.main.php(195): make_rel_links_abs('<div><div class...')\n#1 /server-path-to-b2evo-6.10.1/inc/_blog_main.inc.php(918): require('/server-path-to-b2evo-6.10.1...')\n#2 /server-path-to-b2evo-6.10.1/index.php(67): require('/server-path-to-b2evo-6.10.1...')\n#3 {main}\n  thrown in /server-path-to-b2evo-6.10.1/inc/_core/_url.funcs.php on line 760, referer: https://site.com/b2evo-6.10.1/index.php?blog=4

Or
https://site.com/b2evo-6.10.1/index.php?blog=4&tempskin=_rss2&disp=comments

and in some instances, accessing:
https://site.com/b2evo-6.10.1/index.php?blog=4&tempskin=_atom
error is logged as:
[Sun Jun 10 10:27:12.084135 2018] [:error] [pid 8573] [client xy.stv.abc.d:39220] PHP Fatal error:  Uncaught Error: Class 'UrlHelper' not found in /server-path-to-b2evo-6.10.1/inc/_core/_url.funcs.php:760\nStack trace:\n#0 /server-path-to-b2evo-6.10.1/inc/_core/_misc.funcs.php(311): make_rel_links_abs('<p>Beautiful sp...')\n#1 /server-path-to-b2evo-6.10.1/inc/items/model/_item.class.php(2242): format_to_output('<p>Beautiful sp...', 'htmlfeed')\n#2 /server-path-to-b2evo-6.10.1/inc/items/model/_item.class.php(2182): Item->get_content_teaser(1, false, 'htmlfeed', Array)\n#3 /server-path-to-b2evo-6.10.1/skins/_atom/index.main.php(164): Item->content_teaser(Array)\n#4 /server-path-to-b2evo-6.10.1/inc/_blog_main.inc.php(918): require('/server-path-to-b2evo-6.10.1...')\n#5 /server-path-to-b2evo-6.10.1/index.php(67): require('/server-path-to-b2evo-6.10.1...')\n#6 {main}\n  thrown in /server-path-to-b2evo-6.10.1/inc/_core/_url.funcs.php on line 760, referer: http://site.com/b2evo-6.10.1/index.php

https://site.com/b2evo-6.10.1/index.php?blog=4&tempskin=_atom&disp=comments

Virtual machines in cloud: Debian Stretch AMD64
php --version
PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )
and
apache2 -v
Server version: Apache/2.4.25 (Debian)
Server built:   2018-03-31T08:47:16

php --version
PHP 7.1.11 (cli) (built: Nov 11 2017 04:20:48) ( NTS )
apachectl -v
Server version: Apache/2.4.29 (Unix)
Server built:   Nov 11 2017 02:01:36

Being experienced in both VMs.

Best Professional Regards.

**Comment by yurabakhtin** [comment]
@Metztli Fixed in commit https://github.com/b2evolution/b2evolution/commit/903fbca509a4b5dcf4b73329e87911dafe609d35.
