### ISSUE TITLE
b2evo-6.10.8/Nginx 1.17.0/PHP7.3.5 preg_match(): Compilation failed: invalid range in character class at offset 119 in /var/www/b2evo-6.10.8/inc/_ext/_url_rel2abs.php on line 300

### ISSUE THREAD

**Issue by Metztli** [b2evolution/b2evolution#85]
Niltze [Hello]-
b2evo-6.10.8/Nginx-1.16.0/PHP7.0 had no issues. However, a couple of days ago, upon upgrading to b2evo-6.10.8 and my own builds of Nginx 1.17.0 and PHP7.3.5 (later two built 'the Debian Way' to generate DEBs) Nginx 1.17.0 outputs similar errors as below -- which appear to come in pairs. Notice the two(2) logged entries below:

2019/05/28 18:06:51 [error] 6209#6209: *20981 FastCGI sent in stderr: " in character class at offset 119 in /var/www/b2evo-6.10.8/inc/_ext/_url_rel2abs.php on line 300PHP message: PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 119 in /var/www/b2evo-6.10.8/inc/_ext/_url_rel2abs.php on line 300PHP message: PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 119 in /var/www/b2evo-6.10.8/inc/_ext/_url_rel2abs.php on line 300PHP message: PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 119 in /var/www/b2evo-6.10.8/inc/_ext/_url_rel2abs.php on line 300PHP message: PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 119 in /var/www/b" while reading upstream, client: 46.229.168.140, server: b2evo-6_10_8.blog, request: "GET /index.php/some_blog/?tempskin=_rss2 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "b2evo-6_10_8.blog"
2019/05/28 18:06:51 [error] 6209#6209: *20981 FastCGI sent in stderr: "log/inc/_ext/_url_rel2abs.php on line 300PHP message: PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 119 in /var/www/b2evo-6.10.8/inc/_ext/_url_rel2abs.php on line 300PHP message: PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 119 in /var/www/b2evo-6.10.8/inc/_ext/_url_rel2abs.php on line 300PHP message: PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 119 in /var/www/b2evo-6.10.8/inc/_ext/_url_rel2abs.php on line 300PHP message: PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 119 in /var/www/b2evo-6.10.8/inc/_ext/_url_rel2abs.php on line 300PHP message: PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 119 in /var/www/b2evo-6.10.8/inc/_ext/_url_rel2abs.php on line 300PHP message: PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 119 in /var/www/b2evo-6.10.8/inc/_ext/_url_rel2abs.php on line 300PHP message: PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 119 in /var/www/b2evo-6.10.8/inc/_ext/_url_rel2abs.php on line 300PHP message: PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 119 in /var/www/b2evo-6.10.8/inc/_ext/_url_rel2abs.php on line 300PHP message: PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 119 in /var/www/b2evo-6.10.8/inc/_ext/_url_rel2abs.php on line 300" while reading upstream, client: 46.229.168.140, server: b2evo-6_10_8.blog, request: "GET /index.php/some_blog/?tempskin=_rss2 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "b2evo-6_10_8.blog"

Please note that I have recreated the error by opening relevant URL in a browser and thus triggering those errors; yet published resource displays properly and seems unaffected.

I am aware you do not support Nginx; notwithstanding, the other CMS which name starts with 'D', is not being affected with those nor similar errors. Also, please keep in mind that nginx adoption is exponentially growing --as it is being adopted by large scale sites due to its efficiency.

Best Professional Regards.

**Comment by fplanque** [comment]
> Please note that I have recreated the error by opening relevant URL in a browser and thus triggering those errors

What is the relevant URL exactly?

Can you add a `pre_dump( $xyz );` before the line 300 mentioned in your log in order to know exactly what the string that creates the error is?

**Comment by Metztli** [comment]
> What is the relevant URL exactly?

It happens in any blog collection where 

[b2evo_domain-name]/index.php?blog=N&tempskin=_rss2

where N is a valid blog number

[b2evo_domain-name]/index.php/named-blog/?tempskin=_atom

where named-blog is valid blog name

> Can you add a pre_dump( $xyz );

xyz being a placeholder for what?

Thanks

**Comment by fplanque** [comment]
> xyz being a placeholder for what?

For whatever variables you find on line 300.

**Comment by Metztli** [comment]
Sorry about the delay (but I was glad I held off trying suggestion on live site; instead recreated issue in a similar VirtualBox environment)
...
 pre_dump( $m );
 if ( !preg_match( '!' . $xurl . '!', $url, $m ) )
         return FALSE;
...

2019/06/04 03:16:02 [error] 14811#14811: *28 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: m in /var/www/b2evo/inc/_ext/_url_rel2abs.php on line 300" while reading response header from upstream, client: 192.168.1.74, server: my.blog, request: "GET //index.php?blog=4&tempskin=_rss2 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "my.blog"

2019/06/04 03:27:39 [error] 14811#14811: *32 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: m in /var/www/b2evo/inc/_ext/_url_rel2abs.php on line 300" while reading response header from upstream, client: 192.168.1.74, server: my.blog, request: "GET /index.php?blog=4&tempskin=_atom HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "my.blog"

Neither $xurl nor $url complain about 'Undefined' issue.

Thanks!

**Comment by Metztli** [comment]
I updated my 'Debian way' PHP build to 7.3.6 but issue persists.
php7.3                7.3.6-1         all          server-side, HTML-embedded scripting language (metapackage)
php7.3-cli            7.3.6-1         amd64        command-line interpreter for the PHP scripting language
php7.3-common         7.3.6-1         amd64        documentation, examples and common module for PHP
php7.3-curl           7.3.6-1         amd64        CURL module for PHP
php7.3-fpm            7.3.6-1         amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
php7.3-gd             7.3.6-1         amd64        GD module for PHP
php7.3-intl           7.3.6-1         amd64        Internationalisation module for PHP
php7.3-json           7.3.6-1         amd64        JSON module for PHP
php7.3-mbstring       7.3.6-1         amd64        MBSTRING module for PHP
php7.3-mysql          7.3.6-1         amd64        MySQL module for PHP
php7.3-opcache        7.3.6-1         amd64        Zend OpCache module for PHP
php7.3-readline       7.3.6-1         amd64        readline module for PHP
php7.3-sqlite3        7.3.6-1         amd64        SQLite3 module for PHP
php7.3-xml            7.3.6-1         amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
php7.3-xmlrpc         7.3.6-1         amd64        XMLRPC-EPI module for PHP
php7.3-zip            7.3.6-1         amd64        Zip module for PHP

**Comment by Metztli** [comment]
I am happy to report that as of b2evolution 6.11.4 running on my PHP 7.3.11 FPM and Nginx 1.17.5 builds on Metztli Reiser4 (based on Linux Debian 10 'Buster' AMD64) the issues reported are not being logged anymore, i.e., the problem has been successfully resolved.

Thank you b2evolution team!
