### ISSUE TITLE
intro-cat not showing on front

### ISSUE THREAD

**Issue by jhnpldng** [b2evolution/b2evolution#90]
Fresh installation of 7.1.1-beta. Intro-Cat doesn't show on the front office in the Manual Collection. Widget for it is in place in Item Single container. Intro-Front shows up just fine with the same widget in Front Page Main Area container. 

poorboy2

**Comment by jhnpldng** [comment]
Even with a new Manual collection with some demo content, there is one intro-cat but it will not show on the front of site

**Comment by yurabakhtin** [comment]
Hello @jhnpldng, please note Intro-Cat Item can be displayed only for category and sub-category pages where the Intro-Cat is assigned. I tested demo Manual Collection and I see Intro-Cat items work as expected there. For example, I see demo Intro-Cat here `/index.php/manual/introduction/`.
You can read doc for Intro-Cat here https://b2evolution.net/man/item-types#default-item-types, https://b2evolution.net/man/intro-and-featured-posts#intro-posts, https://b2evolution.net/man/intro-post.
